<?php
if(!defined('ABSPATH')) exit;
function mlb_pg_changelog(){
    echo '<div class="wrap"><div class="mlb-hd"><div class="mlb-hd-i">📜</div><div><h1>Changelog</h1><p>Full version history for DadsFam Music Lessons Booking System</p></div></div>';
    $versions=[
        ['5.3.17','Payment status now shown in cancellation emails','2025',[
            'FIXED:   Cancellation email did not show payment status — the function signature did not accept a pay_status parameter.',
            'FIXED:   All three cancellation email callers updated to pass the current payment status.',
            'RESULT:  Cancellation email now shows payment row: e.g. Payment: EFT Pending, Payment: Failed, Payment: Cancelled — so student knows exactly why the lesson was cancelled.',
            'COVERS:  Edit panel cancel + notify, teacher portal Cancel button, admin Cancel action.',
        ]],
        ['5.3.16','Reverted dynamic payment filtering — all options always shown','2025',[
            'REVERTED: v5.3.15 dynamic payment status filtering removed.',
            'REASON:   A lesson can be confirmed but payment still pending (e.g. EFT awaiting), or cancelled precisely because payment failed — so all payment options must be available for both booking statuses.',
            'RESULT:   Both Confirmed and Cancelled booking statuses show all payment options: N/A, Awaiting Card, EFT Pending, Paid, Failed, Cancelled.',
            'EMAIL LOGIC UNCHANGED: Confirmed + Paid/N/A sends Lesson Booked!. Confirmed + pending/failed sends Lesson Updated. Cancelled sends cancellation email.',
        ]],
        ['5.3.15','Contextual payment status options in edit panels','2025',[
            'ADDED:   Payment Status dropdown now filters dynamically based on Booking Status selection in both admin and teacher portal edit panels.',
            'Confirmed booking options: N/A (no payment needed) or Paid. These are the only logical combinations for a confirmed lesson.',
            'Cancelled booking options: N/A, EFT Pending (unpaid), Payment Failed, Payment Cancelled.',
            'When switching booking status, payment status auto-updates to the most sensible default if the current selection becomes invalid.',
            'Prevents illogical combinations like Confirmed + EFT Pending or Cancelled + Paid.',
        ]],
        ['5.3.14','Booking reference code in Yoco Note field','2025',[
            'ADDED:   Booking confirmation code now included in the Yoco billNote field.',
            'RESULT:  Yoco sale details Note field now shows e.g. "Wackytones — Piano lesson | Ref: 4943E3C7" for easy accounting and reconciliation.',
            'NOTE:    The externalId field was already set to the booking code (used for Yoco API lookups). The Order number in Yoco (#0011 etc.) is Yocos own sequential counter and cannot be overridden.',
        ]],
        ['5.3.13','Contact footer URL shows label not full URL','2025',[
            'CHANGED: URL in email contact footer now shows Contact Us as the link text instead of the full URL.',
            'REASON:  Full URLs in email footers look cluttered. A short label is cleaner and still fully clickable.',
        ]],
        ['5.3.12','📞 Contact footer in all emails','2025',[
            'ADDED:   Contact info footer (from Settings → Contact Info) now appears in EFT bank details email.',
            'ADDED:   Contact info footer now appears in cancellation email.',
            'RESULT:  All 4 email types (Lesson Booked!, Lesson Updated, Lesson Cancelled, EFT Details) now include the contact footer when configured.',
        ]],
        ['5.3.11','🔑 Yoco settings — both keys + beginner-friendly explanation','2025',[
            'ADDED:   Yoco Public Key field (pk_live_ / pk_test_) in Settings → Payments alongside the existing Secret Key.',
            'ADDED:   Clear explanation in the Yoco settings card explaining that these are the exact same keys used in the WooCommerce Yoco plugin.',
            'ADDED:   Step-by-step note: find keys at portal.yoco.com → Settings → Developers → API Keys, or copy from WooCommerce → Payments → Yoco if already configured.',
            'ADDED:   Labels clarify pk_ = Public Key (safe to store) and sk_ = Secret Key (private, used to process payments).',
            'ADDED:   Tip explaining test vs live keys and when to switch.',
        ]],
        ['5.3.10','🐛 Email type logic fix — no Lesson Booked for unresolved payments','2025',[
            'FIXED:   "Lesson Booked!" confirmation email was sent even when payment status was Failed, EFT Pending, or Awaiting Card — contradictory and confusing.',
            'FIX:     "Lesson Booked!" is now only sent when: status=confirmed AND payment is paid OR not_required.',
            'FIX:     Confirmed + pending/failed payment → "Lesson Updated" email (appropriate, no false celebration).',
            'RULE:    Cancelled → cancellation email. Confirmed + settled → Lesson Booked!. Everything else → Lesson Updated.',
        ]],
        ['5.3.9','🐛 Network error fix — undefined function','2025',[
            'FIXED:   Save from edit panel returned "Network error" after v5.3.8.',
            'ROOT CAUSE: mlb_contact_footer_inline() was called inside the email body but never defined — PHP threw a fatal error, the AJAX response was an error page not JSON, and the JS fetch catch block showed "Network error".',
            'FIX:      mlb_contact_footer_inline() function properly defined in email.php before its first use.',
        ]],
        ['5.3.8','🐛 Confirmed booking email always includes payment status','2025',[
            'FIXED:   When teacher sets Booking Status to Confirmed and sends notification, the student now always receives the "Lesson Booked!" confirmation email with the current payment status row.',
            'ROOT CAUSE: The notify routing was checking if payment changed TO paid specifically. If the teacher confirmed a booking without changing payment (e.g. status was already paid, or no payment involved), it fell through to the generic "Lesson Updated" email or sent the confirmation without payment.',
            'FIX:      Simplified routing — cancelled → cancellation email; confirmed → Lesson Booked! with current payment status; anything else → Lesson Updated email.',
            'RESULT:   Confirmed + Paid → Lesson Booked! showing Payment: ✅ Received. Confirmed + N/A → Lesson Booked! with no payment row. Confirmed + EFT Pending → Lesson Booked! showing Payment: 🏦 EFT Pending.',
        ]],
        ['5.3.17','Payment status now shown in cancellation emails','2025',[
            'FIXED:   Cancellation email did not show payment status — the function signature did not accept a pay_status parameter.',
            'FIXED:   All three cancellation email callers updated to pass the current payment status.',
            'RESULT:  Cancellation email now shows payment row: e.g. Payment: EFT Pending, Payment: Failed, Payment: Cancelled — so student knows exactly why the lesson was cancelled.',
            'COVERS:  Edit panel cancel + notify, teacher portal Cancel button, admin Cancel action.',
        ]],
        ['5.3.16','Reverted dynamic payment filtering — all options always shown','2025',[
            'REVERTED: v5.3.15 dynamic payment status filtering removed.',
            'REASON:   A lesson can be confirmed but payment still pending (e.g. EFT awaiting), or cancelled precisely because payment failed — so all payment options must be available for both booking statuses.',
            'RESULT:   Both Confirmed and Cancelled booking statuses show all payment options: N/A, Awaiting Card, EFT Pending, Paid, Failed, Cancelled.',
            'EMAIL LOGIC UNCHANGED: Confirmed + Paid/N/A sends Lesson Booked!. Confirmed + pending/failed sends Lesson Updated. Cancelled sends cancellation email.',
        ]],
        ['5.3.15','Contextual payment status options in edit panels','2025',[
            'ADDED:   Payment Status dropdown now filters dynamically based on Booking Status selection in both admin and teacher portal edit panels.',
            'Confirmed booking options: N/A (no payment needed) or Paid. These are the only logical combinations for a confirmed lesson.',
            'Cancelled booking options: N/A, EFT Pending (unpaid), Payment Failed, Payment Cancelled.',
            'When switching booking status, payment status auto-updates to the most sensible default if the current selection becomes invalid.',
            'Prevents illogical combinations like Confirmed + EFT Pending or Cancelled + Paid.',
        ]],
        ['5.3.14','Booking reference code in Yoco Note field','2025',[
            'ADDED:   Booking confirmation code now included in the Yoco billNote field.',
            'RESULT:  Yoco sale details Note field now shows e.g. "Wackytones — Piano lesson | Ref: 4943E3C7" for easy accounting and reconciliation.',
            'NOTE:    The externalId field was already set to the booking code (used for Yoco API lookups). The Order number in Yoco (#0011 etc.) is Yocos own sequential counter and cannot be overridden.',
        ]],
        ['5.3.13','Contact footer URL shows label not full URL','2025',[
            'CHANGED: URL in email contact footer now shows Contact Us as the link text instead of the full URL.',
            'REASON:  Full URLs in email footers look cluttered. A short label is cleaner and still fully clickable.',
        ]],
        ['5.3.12','📞 Contact footer in all emails','2025',[
            'ADDED:   Contact info footer (from Settings → Contact Info) now appears in EFT bank details email.',
            'ADDED:   Contact info footer now appears in cancellation email.',
            'RESULT:  All 4 email types (Lesson Booked!, Lesson Updated, Lesson Cancelled, EFT Details) now include the contact footer when configured.',
        ]],
        ['5.3.11','🔑 Yoco settings — both keys + beginner-friendly explanation','2025',[
            'ADDED:   Yoco Public Key field (pk_live_ / pk_test_) in Settings → Payments alongside the existing Secret Key.',
            'ADDED:   Clear explanation in the Yoco settings card explaining that these are the exact same keys used in the WooCommerce Yoco plugin.',
            'ADDED:   Step-by-step note: find keys at portal.yoco.com → Settings → Developers → API Keys, or copy from WooCommerce → Payments → Yoco if already configured.',
            'ADDED:   Labels clarify pk_ = Public Key (safe to store) and sk_ = Secret Key (private, used to process payments).',
            'ADDED:   Tip explaining test vs live keys and when to switch.',
        ]],
        ['5.3.10','🐛 Email type logic fix — no Lesson Booked for unresolved payments','2025',[
            'FIXED:   "Lesson Booked!" confirmation email was sent even when payment status was Failed, EFT Pending, or Awaiting Card — contradictory and confusing.',
            'FIX:     "Lesson Booked!" is now only sent when: status=confirmed AND payment is paid OR not_required.',
            'FIX:     Confirmed + pending/failed payment → "Lesson Updated" email (appropriate, no false celebration).',
            'RULE:    Cancelled → cancellation email. Confirmed + settled → Lesson Booked!. Everything else → Lesson Updated.',
        ]],
        ['5.3.9','🐛 Network error fix — undefined function','2025',[
            'FIXED:   Save from edit panel returned "Network error" after v5.3.8.',
            'ROOT CAUSE: mlb_contact_footer_inline() was called inside the email body but never defined — PHP threw a fatal error, the AJAX response was an error page not JSON, and the JS fetch catch block showed "Network error".',
            'FIX:      mlb_contact_footer_inline() function properly defined in email.php before its first use.',
        ]],
        ['5.3.8','🐛 Lesson Booked email fixes','2025',[
            'FIXED:   Payment: ✅ Received row was missing from the "Lesson Booked!" confirmation email — mlb_payment_row() was never inserted into the confirmation email template (the Python replacement silently failed). Now correctly shows Payment status when present.',
            'FIXED:   When teacher confirms a booking (Booking Status = Confirmed) with notify checked, the email now sends "Lesson Booked!" not "Lesson Updated". Any status=confirmed save triggers the full booking confirmation template.',
            'FIXED:   "Contact us" line in confirmation email now shows actual contact details (email, phone, URL) from settings when configured, instead of the generic hardcoded text.',
        ]],
        ['5.3.7','🐛 Payment ✅ Paid missing from confirmation emails','2025',[
            'FIXED:   Confirmation emails (Yoco success, EFT confirmed by teacher, teacher edit notify) were not showing the Payment status row even when payment was paid.',
            'ROOT CAUSE: All three places that call mlb_send_email() after a confirmed payment were calling it without passing the pay_status parameter, so it defaulted to not_required and the Payment row was skipped.',
            'FIX:      mlb_send_email() now receives pay_status = paid in: Yoco return handler, EFT confirm handler, and teacher edit notify handler.',
            'RESULT:   Confirmation emails now show "Payment: ✅ Received" when payment is confirmed — the most important status.',
        ]],
        ['5.3.6','🗂 Bulk select and delete bookings','2025',[
            'ADDED:   Checkbox on every row in Admin → All Bookings — select individual bookings or use Select All in the header.',
            'ADDED:   Dark bulk action bar appears when any rows are checked — shows count and Delete Selected button.',
            'ADDED:   Select All header checkbox supports indeterminate state (dash) when partially selected.',
            'ADDED:   Bulk delete removes rows from the table instantly via AJAX without a page reload.',
            'ADDED:   Same bulk select and delete added to the teacher portal bookings table.',
            'ADDED:   Confirmation dialog shows student names for up to 5 selected bookings before deleting.',
        ]],
        ['5.3.5','🐛 Login bug fix + payment status in emails + contact footer','2025',[
            'FIXED:   Teacher portal password login showed "Incorrect code" error (OTP error message) instead of "Incorrect password" — auth.php was using mlb_err=wrong (OTP) for both failures.',
            'FIXED:   After a failed password attempt, the password form now auto-shows instead of collapsing again.',
            'ADDED:   Payment status row in all confirmation and update emails — shows: ✅ Received, 🏦 EFT pending, 💳 Processing, ❌ Failed.',
            'ADDED:   Contact Info footer in all emails — shows hyperlinked email, phone (tel: link), and URL at the bottom of every email.',
            'ADDED:   Contact Info fields in Admin Settings → General → Contact Info for Emails.',
            'ADDED:   Contact Info fields in Teacher Portal → My Settings → 💰 Rates & Contact.',
        ]],
        ['5.3.4','📧 Student email notifications on booking edit','2025',[
            'ADDED:   "📧 Send email notification to student" checkbox in both the teacher portal and admin edit panels — checked by default.',
            'ADDED:   Smart email routing based on what changed: cancelled → cancellation email; payment marked paid → full confirmation email; anything else → "Booking Updated" email showing new details.',
            'ADDED:   New mlb_send_update_email() function — branded HTML email showing updated lesson details with coral header for confirmed bookings, grey header for cancellations.',
            'CHANGED: Teacher can uncheck the notify box for silent edits (fixing a typo, internal note, etc.) without emailing the student.',
        ]],
        ['5.3.3','🔧 Edit panels aligned between portal and admin','2025',[
            'FIXED:   Teacher portal edit panel was missing the Payment Status dropdown that the admin edit panel has.',
            'ADDED:   Payment Status dropdown in teacher portal edit panel: N/A, Awaiting Card, EFT Pending, Paid, Failed, Cancelled.',
            'FIXED:   mlb_t_save AJAX handler now saves payment_status when teacher edits a booking from the portal.',
            'CHANGED: Both the admin bookings page and the teacher portal edit panel now have identical fields: student info, lesson details, Booking Status, and Payment Status.',
        ]],
        ['5.3.2','✏️ Edit button added to admin bookings page','2025',[
            'ADDED:   ✏️ Edit button on every row in Admin → All Bookings — same slide-up panel as the teacher portal.',
            'ADDED:   Admin edit panel includes Booking Status (Confirmed/Cancelled) AND Payment Status dropdowns so both can be updated together in one save.',
            'ADDED:   Payment Status dropdown in admin edit: N/A, Awaiting Card, EFT Pending, Paid, Failed, Cancelled.',
            'ADDED:   mlb_admin_save_booking AJAX handler (uses manage_options, separate from teacher portal handler).',
            'FIXED:   EFT-confirmed bookings can now be edited, have their status changed, or have payment status corrected directly from the admin.',
        ]],
        ['5.3.1','🐛 EFT email definitive fix','2025',[
            'FIXED:   EFT selected on booking form was always sending the regular "Lesson Booked!" confirmation email instead of the EFT bank details email.',
            'ROOT CAUSE: The payment-aware mlb_ajax_book function was overwritten by an old version during a previous rewrite — the entire payment method branching ($pay_m logic, EFT block, Yoco block) was silently missing. Every booking was falling straight through to mlb_send_email() regardless of which payment method was chosen.',
            'FIX 1:   mlb_ajax_book restored with full payment-aware code: reads payment_method, branches to Yoco checkout / EFT email / standard email correctly.',
            'FIX 2:   Server-side fallback added — if payment_method is missing from POST but only EFT is enabled, $pay_m defaults to eft automatically.',
            'FIX 3:   form.js explicitly reads the checked radio input and sets it on FormData before submission, so the value is never ambiguous.',
        ]],
        ['5.3.0','📅 Weekly calendar booking view','2025',[
            'CHANGED: Booking form sections 2+3 (date picker + slot picker) replaced with an interactive weekly calendar.',
            'ADDED:   Calendar shows all 7 days of the week with every time slot visible at a glance.',
            'ADDED:   Available slots shown in green — click any to select.',
            'ADDED:   Booked/unavailable slots shown in red with strikethrough — not clickable.',
            'ADDED:   Teacher days off shown as greyed-out columns.',
            'ADDED:   Past dates and dates beyond advance booking window are automatically greyed out.',
            'ADDED:   Today column highlighted in amber.',
            'ADDED:   Prev/Next week navigation with Today button.',
            'ADDED:   Prev button disabled when already on current week.',
            'ADDED:   Selected slot highlighted in primary colour with confirmation bar below calendar.',
            'ADDED:   New AJAX endpoint mlb_week_slots returns availability for all 7 days in one call.',
            'ADDED:   Calendar refreshes automatically when instrument is changed.',
            'CHANGED: max-width of booking form widened to 760px to accommodate the week grid.',
        ]],
        ['5.2.3','🐛 EFT email sending wrong confirmation email','2025',[
            'FIXED:   Selecting EFT on the booking form sent the regular "Lesson Booked!" confirmation email instead of the EFT bank details email.',
            'ROOT CAUSE: Payment method was stored in a hidden <input> updated by JavaScript. If JS did not update the field (default state, caching, or JS timing), the value stayed as "none" and the fallback confirmation email fired instead of the EFT flow.',
            'FIX:      Replaced hidden input + JS approach with real <input type="radio" name="payment_method"> elements. Radio inputs are always reliably included in FormData() regardless of JavaScript, so the correct payment method is always sent to the server.',
            'CHANGED:  mlbPickPM() JS function replaced with mlbUpdatePM() — now handles visual highlighting only, not value management.',
        ]],
        ['5.2.2','🐛 Payment column missing from teacher portal','2025',[
            'FIXED:   Payment badge column was missing from the teacher portal bookings table.',
            'ROOT CAUSE: The Python string replacement that should have added the Payment column header and tPayBadge() cell to the JS table builder did not match the exact strings in the file — the tPayBadge function was defined but never called.',
            'ADDED:   Payment badge now shows on every row in the teacher portal: 💳 Paid, 🏦 EFT Pending, 💳 Awaiting Card, ❌ Failed.',
            'ADDED:   ✅ EFT Paid button visible on EFT Pending rows in the teacher portal.',
        ]],
        ['5.2.1','🐛 Payment settings save bug fix','2025',[
            'FIXED:   Payment settings (Enable Yoco, Enable EFT, bank details, Yoco key) were never being saved.',
            'ROOT CAUSE: The Python string replacement that was supposed to inject the payment save lines into the settings save handler targeted the wrong string — the target never matched, so the replacement silently failed and the save lines were omitted entirely.',
            'SYMPTOM:  Settings tab appeared correctly and form fields rendered fine, but clicking "Save All Settings" did not persist pay_yoco, pay_eft, or any payment fields. mlb_pay_enabled() always returned false, so the payment step never appeared on the booking form.',
            'FIX:      Payment save lines now correctly placed immediately before update_option() in the save handler.',
        ]],
        ['5.2.0','💳 Yoco + EFT payments (no WooCommerce)','2025',[
            'ADDED:   Yoco card payment integration — calls Yoco API directly, no WooCommerce required.',
            'ADDED:   EFT / Bank Transfer payment option — slot reserved immediately, bank details emailed to student.',
            'ADDED:   Both payment methods independently toggleable in Settings → 💳 Payments.',
            'ADDED:   Yoco: HMAC-signed success URL prevents fake payment confirmations.',
            'ADDED:   EFT: teacher marks payment received from portal — confirmation email sent automatically.',
            'ADDED:   Payment status badges on every booking row: 💳 Paid / 🏦 EFT Pending / 💳 Awaiting Card / ❌ Failed.',
            'ADDED:   "✅ EFT Paid" button on portal rows awaiting EFT — one click confirms + emails student.',
            'ADDED:   Stats bar in teacher portal shows 🏦 EFT Pending count and outstanding total.',
            'ADDED:   Payment column in Admin → All Bookings.',
            'ADDED:   DB columns: payment_method, payment_status, payment_reference.',
            'ADDED:   New Payments tab in Settings with Yoco secret key (show/hide), test card info, and EFT bank details.',
        ]],
        ['5.1.3','🔐 Email OTP login','2025',[
            'ADDED:   Email OTP (one-time password) login for the teacher portal.',
            'CHANGED: Default login is now "📧 Send Login Code" — a 6-digit code is emailed to the teacher\'s registered address.',
            'ADDED:   6-digit code input with individual boxes, auto-advance between digits, paste support, and arrow key navigation.',
            'ADDED:   Live countdown timer — turns amber at 60 seconds, red at 30 seconds, disables submit on expiry.',
            'ADDED:   Resend code button (appears on OTP step) with 60-second rate limit to prevent spam.',
            'ADDED:   Maximum 5 wrong attempts before lockout — prevents brute-force guessing.',
            'ADDED:   OTP is bcrypt-hashed before storage — plaintext code never touches the database.',
            'ADDED:   Single-use — OTP is deleted immediately on successful verification.',
            'ADDED:   Password login kept as a "🔑 Use password instead" fallback toggle, hidden by default.',
        ]],
        ['5.1.2','⚙️ Teacher portal settings','2025',[
            'ADDED:   ⚙️ My Settings tab in the teacher portal — teachers manage their own schedule without needing WP Admin access.',
            'ADDED:   📅 Lesson Schedule settings: lesson duration, break between lessons (prep/toilet time), advance booking window.',
            'ADDED:   Teaching days & hours: teacher can enable/disable each day of the week and set open/close times per day.',
            'ADDED:   💰 Rates & Instruments: teacher sets price per lesson, currency symbol, and which instruments they teach.',
            'ADDED:   🚫 Days Off & Blocked Dates: teacher adds/removes blocked dates directly from the portal with optional reason.',
            'CHANGED: Settings tab hides the search bar and bookings table cleanly; each section saves independently via AJAX.',
        ]],
        ['5.1.1','🔑 Licensing hourly checks + cancellation emails','2025',[
            'FIXED:   License check interval changed from 24 hours to HOURLY — matching the Invoice Manager and Site Lock plugins exactly.',
            'ADDED:   WP Cron job (dfmlb_hourly_verify) fires every hour so even low-traffic sites are re-verified regularly.',
            'ADDED:   Transient (HOUR_IN_SECONDS) for fast license reads between API calls — transient expiry triggers the next API call automatically.',
            'ADDED:   Force-lock REST endpoint POST /wp-json/dfmlb/v1/force-lock — dadsfam.co.za License Manager can instantly suspend a key; transient is cleared and status set to suspended immediately.',
            'ADDED:   Force-lock authenticated with the stored license key (same approach as Invoice Manager).',
            'ADDED:   Cancellation email sent to the student automatically when teacher cancels a lesson from the portal.',
            'ADDED:   Cancellation email uses same branded HTML table layout as the confirmation email but with a grey header to visually distinguish it.',
            'ADDED:   Cancellation email includes a yellow notice prompting the student to contact and reschedule, with their reference code.',
        ]],
        ['5.1.0','🔑 DadsFam licensing + plugin rename','2025',[
            'CHANGED: Plugin renamed from "Music Lesson Booking System" to "DadsFam Music Lessons Booking System".',
            'ADDED:   DadsFam license integration — Settings → ⭐ License tab.',
            'ADDED:   License activation via POST to dadsfam.co.za REST API (dfmlb product).',
            'ADDED:   License status badge on admin Dashboard (Licensed / Unlicensed / Invalid / Check Failed).',
            'ADDED:   Silent background re-verify every 24 hours — keeps license status current without manual action.',
            'ADDED:   Admin notice shown if license becomes invalid or suspended after a re-verify.',
            'ADDED:   Deactivate button frees up an activation slot on the server.',
            'ADDED:   Re-check Now button for instant manual verification.',
            'ADDED:   Force-lock infrastructure fully in place — ready for Pro feature gating (no features locked yet).',
            'ADDED:   Free vs Pro tier comparison shown in the License tab.',
        ]],
        ['5.0.0','🎛 Teacher portal management + multi-file rebuild','2025',[
            'ADDED:   Full booking management inside the teacher portal — no WP admin needed.',
            'ADDED:   Search bar in portal — find by name, email, phone, or confirmation code.',
            'ADDED:   Four tabs: Upcoming | Today | All | Cancelled (AJAX, no page reload).',
            'ADDED:   Filter by instrument and date range in the portal.',
            'ADDED:   Edit panel — teacher changes all booking details from the portal.',
            'ADDED:   Cancel button — marks cancelled with confirmation, refreshes table instantly.',
            'ADDED:   Delete button — permanently removes with double-confirmation.',
            'CHANGED: Rebuilt as proper multi-file plugin (includes/, shortcodes/, assets/).',
            'FIXED:   Teacher login — DIRECT SQL password storage bypasses all cache layers.',
            'FIXED:   PHP native bcrypt (password_hash/password_verify) — no WP functions in auth path.',
            'ADDED:   Dedicated option (mlb_teacher_pw) decoupled from the settings array.',
            'ADDED:   Legacy PHPass fallback so v1–v4 installs work without resetting password.',
            'ADDED:   Password Tools: Set Password (with instant verify), Test, Reset to Default.',
        ]],
        ['4.2.1','🐛 Critical password hash mismatch fix','2025',[
            'FIXED:   sanitize_text_field() on save vs wp_unslash() on check — hash mismatch causing correct passwords to always be rejected.',
            'ADDED:   Diagnostic tools: Test Password, Reset to teacher123.',
            'ADDED:   Password status indicator in settings.',
        ]],
        ['4.2.0','🎨 WP native auth + colour customisation','2025',[
            'FIXED:   Teacher login rebuilt using wp_set_auth_cookie() — the same mechanism WP uses for its own login.',
            'ADDED:   Teacher user auto-blocked from /wp-admin/ — only sees the portal.',
            'ADDED:   Colour pickers in Settings → Appearance with live preview.',
            'CHANGED: Default warm coral/peach colour scheme for music studio aesthetic.',
        ]],
        ['4.1.0','🔍 Confirmation code + admin search','2025',[
            'ADDED:   Confirmation code column in All Bookings admin table (coloured badge).',
            'ADDED:   Search + filter bar in All Bookings — by name, email, phone, or code.',
            'ADDED:   Filter by instrument and date range.',
            'ADDED:   This Changelog page.',
        ]],
        ['4.0.0','🐛 Email layout + admin tabs fix','2025',[
            'FIXED:   Emails rendered "InstrumentPiano" — flexbox not supported in email clients; rebuilt with HTML table layout.',
            'FIXED:   Admin Settings tabs broken — PHP tag inside echo string caused silent JS syntax error.',
            'CHANGED: Custom fields builder moved into Form Fields tab.',
        ]],
        ['3.0.0','✏️ Custom fields + DB auto-upgrade','2025',[
            'FIXED:   Booking save failed on old DB tables missing student_age / experience_level columns.',
            'ADDED:   Auto-upgrade routine runs dbDelta on every version bump.',
            'ADDED:   Custom fields system — text, long text, dropdown, phone, email, number.',
            'ADDED:   Custom field data saved as JSON per booking; shown in portal and emails.',
        ]],
        ['2.0.0','🖥 Full UI redesign','2025',[
            'FIXED:   Settings nonce mismatch — "link expired" error on save.',
            'FIXED:   Currency hardcoded as "$" — now configurable (default R).',
            'ADDED:   Tabbed settings UI, stat cards, responsive layout.',
            'ADDED:   Blocked Dates admin page.',
            'ADDED:   Optional/required field toggles and custom labels.',
            'ADDED:   Admin notification email on new booking.',
            'ADDED:   Buffer time and max-advance-days settings.',
        ]],
        ['1.0.0','🚀 Initial release','2025',[
            'ADDED:   [music_lesson_booking] and [teacher_lesson_dashboard] shortcodes.',
            'ADDED:   Real-time time slot availability via AJAX.',
            'ADDED:   Overbooking prevention (existing bookings + buffer time).',
            'ADDED:   HTML confirmation email with unique confirmation code.',
            'ADDED:   Business hours configurable per day of week.',
        ]],
    ];
    foreach($versions as $v){
        echo '<div class="mlb-cl-ver"><h3>v'.esc_html($v[0]).' — '.esc_html($v[1]).' <span style="font-weight:400;color:#94a3b8;font-size:12px;">'.esc_html($v[2]).'</span></h3><ul>';
        foreach($v[3] as $note) echo '<li>'.esc_html($note).'</li>';
        echo '</ul></div>';
    }
    echo '</div>';
}
